README.md

- Atualiza README com informações sobre a execução da aplicação usando docker

Atualiza readme sobre o docker

---

server/models/postgres/licitacao.js
server/routes/api/licitacoes.js

Objetivo: conseguir pesquisar informações de uma única licitação

adiciona endpoint para licitações com id

---

.angulardoc.json
.gitignore
client/src/app/novidades/novidades.component.ts
client/src/app/shared/models/novidade.model.ts
client/src/app/shared/services/novidade.service.ts
server/models/postgres/novidade.js
server/routes/api/novidades.js

Depende da aprovação deste [PR](https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/38) do repositário de dados e do #20 deste repositório

120 adiciona empenho as novidades

---

client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.html
client/src/app/shared/models/licitacao.model.ts
server/routes/api/licitacoes.js

A branch estava apresentando problemas ao clicar em detalhes, pois não conseguia acessar os valores contidos na tabela de licitações.

Bugfix leiaute

---

client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.html
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.ts
client/src/app/licitacoes/licitacoes.module.ts
client/src/app/shared/models/licitacao.model.ts
server/models/postgres/contrato.js
server/models/postgres/itensContrato.js
server/models/postgres/licitacao.js
server/routes/api/contratos.js
server/routes/api/licitacoes.js

Necessita da aprovação do PR: https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/47

150 itens de contratos

---

client/src/app/app.module.ts
client/src/app/filter/filter.component.html
client/src/app/filter/filter.component.ts
client/src/app/filter/filter.module.ts
client/src/app/novidades/novidades.component.html
client/src/app/novidades/novidades.component.ts
client/src/app/shared/services/novidade.service.ts
package-lock.json
package.json
server/middlewares/novidades.validator.js
server/routes/api/novidades.js

- Altera endpoint de novidades para realizar filtro de novidades por data
- Adiciona seletores de data (inicial e final) ao componente de filtro
- Adiciona evento para recuperar novidades com base em um novo conjunto de datas
- É preciso ter a versão dos dados gerados pela versão master.

Adiciona filtro de novidades por data

---

client/src/app/app.module.ts
client/src/app/filter/filter.component.html
client/src/app/filter/filter.component.ts

- Adiciona localização PT-BR para a aplicação
- Adiciona limite de datas para o filtro de datas
- Modifica primeiro dia da semana no calendário

Modifica localização da aplicação para PT-BR

---

client/src/app/filter/filter.component.html
client/src/app/filter/filter.component.ts
client/src/app/novidades/novidade/novidade.component.html
client/src/app/shared/services/novidade.service.ts
client/src/styles.scss

- Modifica serviço de novidades para considerar novos agrupamentos para os
tipos de novidade
- Altera componente de filtro
- Altera estilo correspondente aos grupos dos tipos de novidade

Altera os grupos de tipo de novidades para Contratação e Pagamento

---

client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar-info/licitacoes-detalhar-info.component.html
client/src/app/shared/models/licitacao.model.ts
server/models/postgres/licitacao.js

- Adiciona informação do tipo de modalidade de licitação
- Depende da revisão e aprovação do PR de dados https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/63

Adiciona informação do tipo de modalidade de licitação

---

server/routes/api/contratos.js
server/routes/api/licitacoes.js

- Corrige sintaxe de include no endpoint de contratos vigentes
- Adiciona flag de required

Corrige sintaxe de include no endpoint de contratos vigentes

---

client/src/app/municipio/contratos-vigentes/contratos-vigentes.component.html
client/src/app/municipio/contratos-vigentes/contratos-vigentes.component.scss

* Adicionei novos campos de número do contrato e datas de início e fim da vigência do contrato
* Mudei a label de documento para cpf/cnpj

Aprimora lista de contratos vigentes

---

README.md
client/README.md
client/src/app/main/home/home.component.html
client/src/app/shared/components/escolher-municipio/escolher-municipio.component.html
client/src/index.html

Atualiza algumas informações na página inicial e nos metadados do site.
Resolve as tarefas #303, #307 e #308.

Atualiza informações da página inicial e metadados

---

client/src/app/app-routing.module.ts
client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/contratos/info-contrato/info-contrato.component.scss
client/src/app/contratos/info-contrato/info-contrato.component.ts
client/src/app/itens/info-item/info-item.component.html
client/src/app/itens/info-item/info-item.component.scss
client/src/app/itens/info-item/info-item.component.spec.ts
client/src/app/itens/info-item/info-item.component.ts
client/src/app/itens/itens-routing.module.ts
client/src/app/itens/itens.module.ts
client/src/app/shared/components/descricao-item/descricao-item.component.html
client/src/app/shared/components/descricao-item/descricao-item.component.scss
client/src/app/shared/components/descricao-item/descricao-item.component.spec.ts
client/src/app/shared/components/descricao-item/descricao-item.component.ts
client/src/app/shared/components/shared.module.ts
client/src/app/shared/models/itensContrato.model.ts
client/src/app/shared/pipes/pipes.module.ts
client/src/app/shared/pipes/termos-importantes.pipe.spec.ts
client/src/app/shared/pipes/termos-importantes.pipe.ts
client/src/app/shared/services/itens.service.ts
server/models/postgres/itensContrato.js
server/routes/api/contratos.js
server/routes/api/itensContrato.js

* Cria página de detalhes de um item
* Aprimora descrição do item nas tabelas
Depende da PR https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/69

US315 - Cria pagina de detalhes de um item

---

client/src/app/municipio/contratos-vigentes/contratos-vigentes.component.html
client/src/app/municipio/licitacoes-abertas/licitacoes-abertas.component.html
client/src/app/municipio/municipio-routing.module.ts
client/src/app/municipio/municipio.component.html
client/src/app/municipio/novidades/novidades.component.html
client/src/app/shared/components/lista-contratos/lista-contratos.component.html

Resolve tarefas #340, #345 e #346.

Melhora os títulos de contratos, licitações e acontecimentos

---

client/src/app/municipio/contratos-vigentes/contratos-vigentes.component.html
client/src/app/municipio/licitacoes-abertas/licitacoes-abertas.component.html
client/src/app/municipio/licitacoes/licitacoes.component.html
client/src/app/municipio/licitacoes/licitacoes.component.spec.ts
client/src/app/municipio/licitacoes/licitacoes.component.ts
client/src/app/municipio/municipio-routing.module.ts
client/src/app/municipio/municipio.component.html
client/src/app/municipio/municipio.module.ts
client/src/app/municipio/novidades/novidades.component.html
client/src/app/shared/components/lista-contratos/lista-contratos.component.html
client/src/app/shared/models/licitacao.model.ts
client/src/app/shared/services/licitacao.service.ts
server/routes/api/licitacoes.js

Resolve tarefa #347
**Flag**: Depende de PR #113

347 - Lista todas as licitações

---

client/src/app/itens/info-item/info-item.component.html
client/src/app/itens/info-item/info-item.component.scss
client/src/app/shared/components/descricao-item/descricao-item.component.ts

* Deixa as informações do item atual fixas (tarefa #348)
* Remove coluna de diferença com similar (tarefa #351)
* Muda título e adiciona ajuda para a tabela de similares (tarefa #349)

Deixa comparação de itens semelhantes mais clara

---

client/src/app/app.component.ts
client/src/environments/environment.prod.ts
client/src/environments/environment.ts
client/src/index.html

Obs.: O código está o mesmo para ambos os environments pois ainda não temos o ID para produção.

Referencia Google Analytics para o app

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/shared/components/descricao-item/descricao-item.component.html
client/src/app/shared/components/tooltip-ajuda/tooltip-ajuda.component.scss

Resolve o bug #133 e adiciona o ícone de ! na coluna da mediana quando não existem itens suficientes a serem comparados.
**Flag:** Depente do PR #135

366 - Bug fix: itens sem unidade

---

client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar-info/licitacoes-detalhar-info.component.html
client/src/app/shared/components/descricao-item/descricao-item.component.html
client/src/app/shared/models/licitacao.model.ts
server/models/postgres/licitacao.js
server/routes/api/itensContrato.js

-  Modifica coluna com o assunto da licitação para receber mais tipos 
- Depende dos PRs https://github.com/analytics-ufcg/ta-na-mesa/pull/138 e https://github.com/analytics-ufcg/ta-na-mesa/pull/139
- Depende da versão do repo de dados https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/76
- Os dados já processados para o assunto covid estão disponíveis aqui https://drive.google.com/drive/u/0/folders/1YnadTUP8czpXKZNX_4XVthJqCP-Gzlhl

Modifica coluna com o assunto da licitação para receber mais tipos 

---

server.js
server/models/postgres/fornecedor.js
server/routes/api/fornecedores.js

- Adiciona consultas para fornecedores na API
- Adiciona endpoint que recupera informações de um fornecedor específico
- Adiciona endpoint que lista todos os fornecedores do banco de dados.

Adiciona consultas para fornecedores na API

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/shared/models/contratoLicitacao.model.ts

- Adiciona descrição do contrato na tela de detalhes do contrato

Adiciona descrição do contrato na tela de detalhes do contrato

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/contratos/info-contrato/info-contrato.component.ts
client/src/app/itens/info-item/info-item.component.html
client/src/app/itens/info-item/info-item.component.ts
client/src/app/municipio/licitacoes/licitacoes.component.html
client/src/app/municipio/licitacoes/licitacoes.component.ts
client/src/app/shared/components/lista-contratos/lista-contratos.component.html
client/src/app/shared/components/lista-contratos/lista-contratos.component.ts
client/src/app/shared/directives/ordenavel.directive.ts

- Define critério de ordenação inicial para as tabelas da aplicação

Define critério de ordenação inicial para as tabelas da aplicação

---

server/routes/api/tipoNovidades.js

Fixes https://github.com/analytics-ufcg/ta-na-mesa/issues/29

Remove duplicação nos endpoints de novidades

---

server/routes/api/contratos.js

Fixes https://github.com/analytics-ufcg/ta-na-mesa/issues/123

Recupera os contratos com vencimento no dia atual para a lista de contratos vigentes

---

client/src/app/shared/components/busca-municipio/busca-municipio.component.html
client/src/styles.scss

Importante: o background da tabela de itens não foi afetado por essas alterações.

Adiciona navbar e backgrounds estáticos na impressão 

---

client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.html
client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.ts
client/src/app/shared/models/fornecedor.model.ts
server/models/index.js
server/models/postgres/cnae.js
server/models/postgres/cnaeSecundario.js
server/models/postgres/dadosCadastrais.js
server/models/postgres/fornecedor.js
server/models/postgres/socios.js
server/routes/api/fornecedores.js

- Adiciona enderenço, contato e informações cadastrais
- Adiciona lista de sócios e lista de atividades econômicas
- Depende da versão dos dados geradas pelo PR https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/92

Adiciona informações da receita na tela de fornecedores

---

client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.html
server/models/index.js
server/models/postgres/dadosCadastrais.js
server/models/postgres/naturezaJuridica.js
server/routes/api/fornecedores.js

- Adiciona informações do porte da empresa e da natureza jurídica
- Depende da versão dos dados geradas pela versão do PR https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/94

Adiciona informações do porte da empresa e da natureza jurídica

---

client/src/app/contratos/info-contrato/info-contrato.component.html
server/models/postgres/itensContrato.js

- Não compara itens que são serviços
Resolve issue https://github.com/analytics-ufcg/ta-na-mesa/issues/196

Não compara itens que são serviços

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.html
client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.scss
client/src/app/shared/models/contratoLicitacao.model.ts
client/src/app/shared/models/fornecedor.model.ts
server/models/index.js
server/models/postgres/alerta.js
server/models/postgres/contrato.js
server/models/postgres/fornecedor.js
server/models/postgres/tipoAlerta.js
server/routes/api/contratos.js
server/routes/api/fornecedores.js

- Adiciona alertas nas páginas do fornecedor e da compra
- Assume a revisão prévia do PR https://github.com/analytics-ufcg/ta-na-mesa/pull/193
- Depende da versão dos dados gerada na versão dos dados https://github.com/analytics-ufcg/ta-na-mesa-dados/pull/96

Adiciona Alertas nas páginas do fornecedor e da Compra

---

client/src/app/shared/components/barra-titulo/barra-titulo.component.scss

- Ajusta posição do componente da barra de título

Ajusta posição do componente da barra de título

---

client/src/app/alertas/alertas.component.html
client/src/app/alertas/card-alerta/card-alerta.component.html

- Corrige formatação dos arquivos de alertas

Corrige formatação dos arquivos de alertas

---

client/src/app/alertas/alertas.component.html
client/src/app/alertas/alertas.component.ts
client/src/app/alertas/alertas.module.ts
client/src/app/alertas/card-alerta/card-alerta.component.html
client/src/app/alertas/filtro-alertas/filtro-alertas.component.html
client/src/app/alertas/filtro-alertas/filtro-alertas.component.scss
client/src/app/alertas/filtro-alertas/filtro-alertas.component.spec.ts
client/src/app/alertas/filtro-alertas/filtro-alertas.component.ts
client/src/app/shared/services/alerta.service.ts

- Adiciona filtro de alertas
- Cria componente do filtro
- Cria lógica de filtro no serviço de alertas
- Adiciona lógica de atualização da url para a pesquisa por nome 
- Assume que o PR https://github.com/analytics-ufcg/ta-na-mesa/pull/204 foi revisado e aprovado

Adiciona filtro para a página de alertas

---

client/src/app/alertas/alertas.component.html
client/src/app/alertas/alertas.component.ts
client/src/app/alertas/alertas.module.ts
client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.html
client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.spec.ts
client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.ts
client/src/app/alertas/card-alerta/alerta-item-atipico/alerta-item-atipico.component.html
client/src/app/alertas/card-alerta/alerta-item-atipico/alerta-item-atipico.component.spec.ts
client/src/app/alertas/card-alerta/alerta-item-atipico/alerta-item-atipico.component.ts
client/src/app/alertas/card-alerta/card-alerta.component.html
client/src/app/alertas/card-alerta/card-alerta.component.scss
client/src/app/alertas/card-alerta/card-alerta.component.ts
client/src/app/alertas/filtro-alertas/filtro-alertas.component.html
client/src/app/alertas/filtro-alertas/filtro-alertas.component.scss
client/src/app/alertas/menu-alerta/menu-alerta.component.html
client/src/app/alertas/menu-alerta/menu-alerta.component.scss
client/src/app/alertas/menu-alerta/menu-alerta.component.spec.ts
client/src/app/alertas/menu-alerta/menu-alerta.component.ts
client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.html
client/src/app/shared/models/alerta.model.ts
client/src/app/shared/models/tipoAlerta.model.ts
client/src/app/shared/services/alerta.service.ts
client/src/styles.scss
server/models/postgres/alerta.js
server/models/postgres/tipoAlerta.js
server/routes/api/alertas.js
server/routes/api/contratos.js
server/routes/api/fornecedores.js

Modificações:
- alteração do endpoint para recuperar novas informações sobre os alertas;
- novo layout para os cards;
- endpoint para recuperar todos os tipos de alerta;
- adição do menu lateral;
- filtragem pelo menu lateral e pelo input de busca.

Adiciona o novo layout da pagina de alertas

---

server/models/postgres/item-atipico.js
server/routes/api/contratos.js

Depende de: https://github.com/analytics-ufcg/ta-de-pe-dados/pull/104

Adiciona novas colunas ao modelo de itens atipicos

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/contratos/info-contrato/info-contrato.component.ts
client/src/app/shared/components/descricao-item/descricao-item.component.html
client/src/app/shared/components/descricao-item/descricao-item.component.scss
client/src/app/shared/components/descricao-item/descricao-item.component.ts
client/src/app/shared/models/itensContrato.model.ts

Modificações:
- Mensagem de item atípico;
- Adição de um novo formato no momento da impressão.

Altera tooltip de itens atipicos

---

client/src/app/busca/busca-compra/busca-compra.component.html
client/src/app/busca/busca-item/busca-item.component.html
client/src/app/busca/busca-municipio/busca-municipio.component.html
client/src/app/busca/busca-municipio/busca-municipio.component.spec.ts
client/src/app/busca/busca-municipio/busca-municipio.component.ts
client/src/app/busca/busca-routing.module.ts
client/src/app/busca/busca.component.html
client/src/app/busca/busca.component.spec.ts
client/src/app/busca/busca.component.ts
client/src/app/busca/busca.module.ts
client/src/app/shared/components/busca-municipio/busca-municipio.component.scss
client/src/app/shared/components/escolher-municipio/escolher-municipio.component.ts
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.html
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.ts
client/src/app/shared/enum/tipo-busca.enum.ts
client/src/app/shared/models/municipio.model.ts
client/src/app/shared/services/lista.service.ts
client/src/app/shared/services/municipio.service.ts
server/routes/api/orgaos.js

-  Adiciona página única de busca com abas para entidades de produtos e contratos
-  Adiciona página de busca por município

Adiciona página única de busca

---

client/src/app/shared/components/lista-contratos/lista-contratos.component.html
client/src/app/shared/services/lista.service.ts
server/routes/api/contratos.js

Modificações: 
- Adiciona filtro por cidade na aba de contratos;
- Filtro pelo núm. do contrato na aba contratos; 
- Busca por contratos na home pelo num. completo do contrato.

628-Adiciona filtro por cidade e pelo núm. do contrato

---

client/src/app/shared/components/descricao-item/descricao-item.component.html
client/src/app/shared/components/descricao-item/descricao-item.component.scss
client/src/app/shared/components/lista-contratos/lista-contratos.component.html
client/src/app/shared/components/lista-contratos/lista-contratos.component.scss
client/src/styles.scss
server/routes/api/contratos.js

Alterações nas páginas listagem dos contratos e informações dos contratos.

Substitui ícones de alertas por badges

---

client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/contratos/info-contrato/info-contrato.component.ts
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar-info/licitacoes-detalhar-info.component.html
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.html
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.ts
client/src/app/shared/components/lista-contratos/lista-contratos.component.html
client/src/app/shared/models/contratoLicitacao.model.ts
client/src/app/shared/models/licitacao.model.ts
server/models/postgres/contrato.js
server/models/postgres/licitacao.js
server/routes/api/contratos.js

- Realiza modificações para receber dados do TCE-PE e de outros estados

Ajusta site para receber dados do TCE-PE e de outros estados

---

client/src/app/alertas/alertas.component.ts
client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.html
client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.ts
client/src/app/alertas/card-alerta/card-alerta.component.html
client/src/app/alertas/filtro-alertas/filtro-alertas.component.html
client/src/app/alertas/filtro-alertas/filtro-alertas.component.ts
client/src/app/contratos/info-contrato/info-contrato.component.ts
client/src/app/shared/services/alerta.service.ts
client/src/styles.scss
server/routes/api/alertas.js

- Filtra alertas por estado
- Exibe corretamente a diferença em dias entre a data de abertura da empresa e a data do primeiro contrato
Depende da revisão do PR de dados
https://github.com/analytics-ufcg/ta-de-pe-dados/pull/126

Filtra alertas por estado

---

client/src/app/main/home/home.component.html
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.scss

Alterações:
- Adiciona texto paga indicar que também existem dados de Pernambuco;
- Ajusta tamanho do input de busca (testar Moto G4).

687 Ajusta elementos (texto sobre dados e input de busca) na página inicial

---

client/src/app/contratos/info-contrato/info-contrato.component.ts
server/models/postgres/item-atipico.js
server/models/postgres/itensContrato.js
server/routes/api/itensContrato.js

A forma anterior poderia causar problemas, pois dependia de informações que poderiam não estar disponíveis.

Corrige acesso aos itens atípicos

---

client/src/app/alertas/card-alerta/alerta-abertura-empresa/alerta-abertura-empresa.component.html
client/src/app/contratos/info-contrato/info-contrato.component.html
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar.component.html
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.html

- Altera case dos municípios
- Muda texto no card dos alertas com diferença negativa de abertura
Closes #333
Closes #334

Altera case dos municípios

---

client/src/app/busca/busca-municipio/busca-municipio.component.html
client/src/app/municipio/contratos-vigentes/contratos-vigentes.component.ts
client/src/app/municipio/licitacoes/licitacoes.component.ts
client/src/app/municipio/municipio-routing.module.ts
client/src/app/municipio/municipio.component.html
client/src/app/municipio/municipio.component.ts
client/src/app/municipio/novidades/novidades.component.ts
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.ts
client/src/app/shared/models/buscavel.model.ts
client/src/app/shared/models/municipio.model.ts
client/src/app/shared/services/contrato.service.ts
client/src/app/shared/services/licitacao.service.ts
client/src/app/shared/services/lista.service.ts
client/src/app/shared/services/municipio.service.ts
server.js
server/models/index.js
server/models/postgres/municipio.js
server/models/postgres/orgao.js
server/routes/api/contratos.js
server/routes/api/licitacoes.js
server/routes/api/municipios.js
server/routes/api/orgaos.js

A página e subpáginas de município devem considerar a slug da URL do município

Cria e modifica chamadas com a nova API de municípios

---

client/src/app/busca/busca-municipio/busca-municipio.component.html
client/src/app/busca/busca-municipio/busca-municipio.component.ts
client/src/app/municipio/licitacoes/licitacoes.component.ts
client/src/app/shared/components/busca-municipio/busca-municipio.component.ts
client/src/app/shared/components/escolher-municipio/escolher-municipio.component.ts
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.ts

- Remove funções que recuperam e salvam o município no Local Storage

Remove funções que recuperam e salvam o município no Local Storage

---

server/routes/api/fornecedores.js

- Adiciona endpoint de busca dos fornecedores, retornando CNPJ/CPF, nome do fornecedor, total de contratos e data do primeiro contrato.

393 consulta fornecedores

---

client/src/app/busca/busca-fornecedor/busca-fornecedor.component.html
client/src/app/busca/busca-fornecedor/busca-fornecedor.component.spec.ts
client/src/app/busca/busca-fornecedor/busca-fornecedor.component.ts
client/src/app/busca/busca-routing.module.ts
client/src/app/busca/busca.component.html
client/src/app/busca/busca.module.ts
client/src/app/fornecedores/info-fornecedor/info-fornecedor.component.html
client/src/app/licitacoes/licitacoes-detalhar/licitacoes-detalhar-nav/licitacoes-detalhar-nav.component.html
client/src/app/municipio/municipio.component.html
client/src/app/shared/components/input-busca-geral/input-busca-geral.component.ts
client/src/app/shared/services/fornecedor.service.ts
client/src/app/shared/services/lista.service.ts
client/src/styles.scss

Adicionando o nome do município aos contratos do fornecedor e criando tela de resultado da pesquisa a fornecedores.

397 resultados fornecedores

---

client/src/app/shared/services/fornecedor.service.ts

- Desconsidera pontuação especial na pesquisa por fornecedor. Isso faz com que pesquisas pelo CNPJ com pontuação sejam possíveis.

Desconsidera pontuação especial na pesquisa por fornecedor

---

client/src/app/alertas/alertas.component.html
client/src/app/alertas/card-alerta/card-alerta.component.html
client/src/app/alertas/card-alerta/card-alerta.component.ts
client/src/app/alertas/filtro-alertas/filtro-alertas.component.html
client/src/app/shared/services/alerta.service.ts
server/models/postgres/fornecedor.js
server/routes/api/alertas.js

- Corrige filtro por estado para a página da malha fina

Corrige filtro por estado para a página da malha fina

---

client/src/app/alertas/alertas.component.ts
client/src/app/alertas/menu-alerta/menu-alerta.component.ts

- Adiciona filtro do tipo de alerta na URL da malha fina
- Adiciona filtro por estado na URL da malha fina
- Depende da revisão e aprovação do PR https://github.com/analytics-ufcg/ta-de-pe/pull/381
closes #362 #350

Alterar URL de acordo com o filtro do tipo de alerta selecionado e reseta paginação após mudança de filtro
